
									<div class="viewResult">
                                    	<p>
	                                        <span class="viewTitre">Conditions g&eacute;n&eacute;rales d'utilisation du site</span> 
                                      	</p>          

   										<p style="clear:both">
                                            <span class="viewTexte"></span> 
                                         </p>
									</div>
									<p style="clear: both;height:5px;"></p>
                                    <div class="ajaxZone">  
<div class="contenuPage">
    <a name="conditions"></a>

    <ul class="conditions"> 
    
        <li><a href="#1">1 - Acceptation des conditions d'utilisation</a></li>
        
        <li><a href="#2">2 - Description du service</a></li>
        <li><a href="#3">3 - Obligation d'inscription</a></li>
        <li><a href="#4">4 - Politique de Ilay NOSY en matière de vie privée</a></li>
        <li><a href="#5">5 - Compte d'utilisateur, mot de passe et sécurité</a></li>
        <li><a href="#6">6 - Comportement des utilisateurs et règles déontologiques appliquées dans les rejets d'annonces</a></li>
        <li><a href="#7">7 - Recommandation particulière aux utilisateurs internationaux</a></li>
        <li><a href="#8">8 - Contenu accessible à tous sur Ilay NOSY</a></li>
        <li><a href="#9">9 - Indemnisation</a></li>
        <li><a href="#10">10 - Interdiction de revendre le service</a></li>
        <li><a href="#11">11 - Règles générales en matière d'utilisation et de stockage</a></li>
        <li><a href="#12">12 - Modification de service</a></li>
        <li><a href="#13">13 - Résiliation</a></li>
        <li><a href="#14">14 - Relation avec les annonceurs</a></li>
        <li><a href="#15">15 - Liens</a></li>
        <li><a href="#16">16 - Droit de propriété de Ilay NOSY</a></li>
        <li><a href="#17">17 - Garanties</a></li>
        <li><a href="#18">18 - Limitation de responsabilité</a></li>
        <li><a href="#19">19 - Avertissement spécifique pour les services concernant les questions financières</a></li>
        <li><a href="#20">20 - Notification</a></li>
        <li><a href="#21">21 - Informations afférentes aux marques déposées</a></li>
        <li><a href="#22">22 - Droits de propriété intellectuelle</a></li>
        <li><a href="#23">23 - Divers</a></li>
        <li><a href="#24">24 - Informations suppl&eacute;mentaires</a></li>

    </ul>
    
    <a name="1"></a>
    <p class="titre"><b>1 - Acceptation des conditions d'utilisation</b></p><br/>
    <p><b>Ilay NOSY</b> vous fournit ses services sous réserve que vous vous engagiez à respecter les présentes conditions d'utilisation (ci-après dénommées « Conditions d'utilisation ») que <b>Ilay NOSY</b> sera libre de modifier à tout moment. Il vous est donc conseillé de vous référer régulièrement à la dernière version des Conditions d'utilisation disponible en permanence à l'adresse suivante : <a href="{jurl 'static~staticFo_staticPage', array('stat'=>4)}" title="Conditions d'utilisation du site">Conditions d'utilisation du site</a>. De plus, l'utilisation de certains services de Ilay NOSY peut nécessiter le respect de règles ou lignes de conduite additionnelles et spécifiques qui seront indiquées dans une charte disponible sur le site. Ces règles et lignes de conduite sont réputées faire partie intégrante des Conditions d'utilisation. Enfin il est précisé que <b>Ilay NOSY</b> peut proposer d'autres services pour lesquels des conditions d'utilisation spécifiques devront être acceptées avant toute utilisation. Dans ces hypothèses, les présentes Conditions d'utilisation ne s'appliqueront pas.</p><br/>
    <p class="droite"><a class="haut" href="#conditions">haut &uArr;</a></p>
    
    <a name="2"></a>
    <p class="titre"><b>2 - Description du service</b></p><br/>
    <p><b>Ilay NOSY</b> fournit actuellement à ses utilisateurs un vaste choix de services en ligne parmi lesquels, notamment, la possibilité de déposer des annonces, des forums, des commentaires, du contenu personnalisé tel que messages, textes, dossiers, visuels, images, photos, vidéos, sonorités, et autres et des programmes de marque <b>Ilay NOSY</b> disponibles sur son réseau de services (ci-après dénommés collectivement les « Services »). Sauf disposition expresse contraire, toute nouvelle caractéristique qui améliore ou augmente un ou plusieurs services existants ou tout nouveau service lancé par Ilay NOSY seront soumis aux présentes Conditions d'utilisation. Vous avez conscience et acceptez le fait que le Service vous est fourni « en l'état » et que <b>Ilay NOSY</b> ne peut être tenu pour responsable de l'opportunité, la suppression, le défaut de livraison ou de stockage des communications ou des installations personnalisées des utilisateurs.</p><br/>
    <p>Afin d'utiliser le Service, il vous faut un accès à l'Internet, soit directement, soit par l'intermédiaire de systèmes ayant un accès à du contenu fourni sur Internet, étant précisé que les éventuels frais correspondants sont à votre seule charge. De plus, vous devez vous munir de tout matériel nécessaire, et notamment d'un ordinateur, d'un modem ou de tout autre outil de connexion, afin d'assurer cette connexion au réseau Internet. Il vous faut être conscient que, dans certaines zones du Service, est diffusé du contenu réservé aux adultes et dont l'accès est donc réservé aux utilisateurs de 18 ans et plus.</p><br/>
    <p>Par ailleurs, vous êtes informé que toute consultation, affichage, téléchargement et/ou transmission de sites, de pages référencées, notamment à l'occasion de vos recherches sur d'autres Sites et Services que ceux de <b>Ilay NOSY</b>  et considérés comme illicites au regard du droit malgache, vous sont interdites et que la violation de ces interdictions est susceptible d'entraîner des poursuites judiciaires et des sanctions à votre encontre.</p>
    <br/>
    <p class="droite"><a class="haut" href="#conditions">haut &uArr;</a></p>
    
    <a name="3"></a>
    <p class="titre"><b>3 - Obligation d'inscription</b></p><br/>
    <p>Par l'utilisation faite du Service vous acceptez de : </p>
    <p>(a) fournir des informations vraies, exactes, à jour et complètes sur vous-même comme demandé dans le formulaire d'inscription au Service (ces informations étant ci-après dénommées les « Données d'Inscription ») </p>
    <p> (b) maintenir et remettre à jour régulièrement les Données d'Inscription afin de les conserver vraies, exactes, à jour et complètes. </p>
    <p>Dans l'hypothèse où vous fourniriez des informations fausses, inexactes, périmées ou incomplètes, <b>Ilay NOSY</b> serait en droit de suspendre ou de résilier votre compte et de vous refuser immédiatement et pour le futur l'accès à tout ou partie du Service.<b>Ilay NOSY</b> est soucieux du respect de la sécurité et de la vie privée de ses utilisateurs et plus particulièrement des enfants. C'est pourquoi les parents sont invités à surveiller l'utilisation faite par leurs enfants de l'accès à l'Internet et à garder présent à l'esprit que le Service est conçu pour toucher un large public et qu'en leur qualité de tuteur légal il est de la responsabilité des parents de déterminer quel Service est ou non approprié pour leur(s) enfant(s) et de surveiller l'utilisation qu'ils en font.
    </p>
    <p><br/>
    </p>
    <p class="droite"><a class="haut" href="#conditions">haut &uArr;</a></p>
    
    <a name="4"></a>
    <p class="titre"><b>4 - Politique de Ilay NOSY en matière de vie privée</b></p><br/>
    <p>Les Données d'Inscription et éventuellement d'autres informations à votre sujet sont traitées dans le cadre des principes mis en oeuvre par <b>Ilay NOSY</b> pour le traitement des données personnelles de ses utilisateurs.  Nous vous rappelons que, conformément à la Loi n° 78-17 du 6 janvier 1978, dite Loi Informatique et Liberté, vous disposez d'un droit de consultation, de modification et de retrait de toutes données personnelles portées à la connaissance de Ilay NOSY lors de l'utilisation du Service. Ainsi, vous pouvez exiger que soient rectifiées, complétées, clarifiées, mises à jour ou effacées les informations le concernant qui sont inexactes, incomplètes, équivoques, périmées ou dont la collecte ou l'utilisation, la communication ou   la conservation est interdite, qu'il peut exercer auprès de Ilay NOSY, soit par   courrier à l'adresse postale suivante :</p>
    <br/>
    <p id="centrer"><b>Société Ilay NOSY SARL<br/>
     Agence de publici&eacute; &amp; R&eacute;gie publicitaire de m&eacute;dias</b><br/> 
       Lot VA 26 K Pr&egrave;s Tsiadana<br/>
      101 Antananarivo - Madagascar</p><br/>
    <p>A la clôture du Compte et à toute fin de preuves, les données   concernant l'utilisateur sont conservées confidentiellement et à titre   d'archivage, pour une durée fixée par <b>Ilay NOSY</b>.</p>
    <br/>
    <p>Enfin, nous vous informons que nous nous réservons le droit d'utiliser les Adresses IP collectées conformément aux dispositions contenues dans notre Centre d'Informations sur les Données Personnelles tant pour (i) identifier les Internautes lorsque nous y sommes contraints par une autorité judiciaire, des autorités de police, par toute autorité administrative indépendante et de manière générale par toute autorité administrative habilitée par la Loi, que pour (ii) identifier les Internautes qui contreviendraient aux présentes conditions générales d'utilisation de notre Site et de nos Services. Dans cette dernière hypothèse, nous serons ainsi en mesure de transmettre votre adresse IP aux fournisseurs d'accès aux fins d'identification (et obtenir ainsi votre radiation éventuelle), voire, si nous l'estimions nécessaire compte tenu de la nature du non respect des présentes, transmettre votre adresse IP directement auprès des autorités compétentes.</p><br/>
    <p>En aucun cas, Ilay NOSY ne partagera ni ne divulguera vos données personnelles, excepté si vous l'avez accepté lors de votre identification sur le site de Ilay NOSY. Ilay NOSY et ses partenaires contractuels peuvent vous envoyer des informations dans le cadre d'opérations promotionnelles précises et ponctuelles (des nouveautés, des offres de déstockage, des exclusivités, des bonnes affaires...). Ces partenaires sont spécialement choisis par Ilay NOSY et sont reconnus pour la qualité de leurs produits et services. Si vous préférez ne pas recevoir les offres que nous sélectionnons pour vous ou que nos partenaires sont susceptibles de vous adresser, vous pouvez l'indiquer en nous contactant par email, ou, ultérieurement, à tout moment, sur le site Ilay NOSY dans la rubrique contact ou par courrier postal.</p>
    <br/>
    <p class="droite"><a class="haut" href="#conditions">haut &uArr;</a></p>
    
    <a name="5"></a>
    <p class="titre"><b>5 - Compte d'utilisateur, mot de passe et sécurité</b></p><br/>
    <p>A l'issue de la procédure d'inscription, vous transmetez un nom de compte ( votre email, qui est unique ) et un mot de passe. Vous êtes seul responsable de la conservation du caractère confidentiel de vos compte et mot de passe et de toutes actions qui pourront être faites sous votre compte et/ou avec votre mot de passe. Vous vous engagez (i) à informer immédiatement <b>Ilay NOSY</b> de toute utilisation non autorisée de votre compte et/ou de votre mot de passe et/ou de toute atteinte à la sécurité, et (ii) à vous assurer qu'à l'issue de chaque session vous vous déconnectez explicitement. Ilay NOSY ne pourra être tenu responsable de toute perte ou dommage survenant en cas de manquement aux obligations du présent paragraphe.</p><br/>
    <p class="droite"><a class="haut" href="#conditions">haut &uArr;</a></p>
    
    <a name="6"></a>
    <p class="titre"><b>6 - Comportement des utilisateurs et règles déontologiques appliquées dans les rejets d'annonces</b></p><br/>
    <p>Vous êtes conscient que toutes les informations, données, textes, logiciels, musiques, sons, photographies, images, vidéos, messages ou tous autres matériels (ci-après dénommés collectivement le « Contenu ») qu'ils soient portés à la connaissance du public ou transmis de manière privée, sont sous la seule responsabilité de la personne ayant émis ce Contenu. Vous seul, et non <b>Ilay NOSY</b>, êtes entièrement responsable du Contenu que vous affichez, téléchargez, envoyez par courrier électronique (ci-après « e-mail ») ou transmettez de toute autre manière par le Service. <b>Ilay NOSY</b> n'exerce pas de contrôle du Contenu transmis via le Service et en conséquence ne garantit pas l'opportunité, la licéité, la probité ou la qualité de ce Contenu. En toutes hypothèses, <b>Ilay NOSY</b> ne pourra en aucun cas être tenu pour responsable du Contenu, notamment<b> du caractère illégal du Contenu au regard de la réglementation en vigueur</b>, d'erreur ou d'omission dans tout Contenu, de toute perte ou dommage consécutifs à l'utilisation de tout Contenu affiché, transmis pas e-mail ou de toute autre manière via le Service.</p><br/>
    <p><b>Vous vous interdisez de :</b></p><br/>
    <p><b>a)</b> proposer plusieurs biens dans le texte d'une même annonce.</p><br/>
    <p><b>b)</b> déposer une même annonce dans plusieurs départements (localit&eacute;s) ou dans plusieurs catégories. </p>
    <br/>
    <p><b>c)</b> d'insérer une URL dans le titre de l'annonce</p><br/>
    <p><b>d)</b> d'insérer des mots-clés dans l'annonce. Seul le texte décrivant le bien est autorisé</p><br/>
    <p><b>e) de proposer la vente de produits contrefaits.</b> Seule la diffusion d'annonces proposant la vente de produits originaux est autorisée (appareils électroniques, DVD, CD, jeux vidéo, logiciels informatiques, cartes, vêtements de marque et des accessoires de marque, montres ...). La vente de copie est considérée par les Tribunaux comme de la contrefaçon.De plus, Nous informons les internautes désireux de diffuser des annonces liées à l’industrie du luxe sur le site Ilay NOSY.com, qu’il est illégal de proposer à la vente des produits revêtus de marques, notamment en matière de parfumerie et de cosmétologie, marques dont les titulaires sont les créateurs d’une réseau de distribution sélective ou agréée, comme c'est le cas entre autre pour les sociétés Parfums Christian Dior, Kenzo Parfums, Parfums Givenchy, Guerlain et Chanel. Ainsi que cela est systématiquement rappelé sur le packaging, de tels produits ne peuvent être vendus que par des distributeurs agréés. Il est également interdit de proposer des parfums et cosmétiques indiquant une concordance ou tout rapprochement explicite ou implicite avec les produits authentiques revêtus d'une marque. Toute annonce qui contreviendrait à ces interdictions, destinées tant à lutter contre la contrefaçon, qu’à assurer le respect des règles de la distribution sélective, sera supprimée sans délai et les données permettant d’identifier l'auteur de l'annonce seront susceptibles, sur réquisition judiciaire, d’être transmises aux titulaires des marques et, le cas échéant, aux autorités compétentes.</p>
    <br/>
    <p><b>f)</b> télécharger, envoyer, transmettre par e-mail ou de toute autre manière tout Contenu qui soit illégal, nuisible, menaçant, abusif, constitutif de harcèlement, diffamatoire, vulgaire, obscène, menaçant pour la vie privée d'autrui, haineux, raciste, ou autrement répréhensible</p><br/>
    <p><b>g)</b> consulter, afficher, télécharger, transmettre, tout Contenu qui serait contraire à la loi en vigueur &agrave; Madagascar. Ainsi, si dans le cadre d'une recherche conduite sur www.<b>Ilay NOSY</b>.com à partir d'une arborescence, de mots clefs, le résultat de celle-ci vous amenait à pointer sur des sites, des pages ou des forums dont le titre et/ou les contenus constituent une infraction à la loi malgache, ainsi en est-il notamment de ceux relatifs à la pédophilie, aux ventes d'organes, aux ventes de substances illicites ou de tout autre objet et/ou prestations illicites, faisant l'apologie du terrorisme, des crimes de guerre, du nazisme, vous devez immédiatement interrompre votre consultation du site concerné sauf à encourir les sanctions prévues par la législation malgache et à répondre des actions en justice initiées à votre encontre</p><br/>
    <p><b>h)</b> porter atteinte d'une quelconque manière aux utilisateurs mineurs</p><br/>
    <p><b>i)</b> transmettre tout Contenu qui pourrait être constitutif, sans que ce qui suit ne soit limitatif, d'incitation à la réalisation de crimes et délits ; de provocation à la discrimination, à la haine ou à la violence en raison de la race, de l'ethnie ou de la nation ; d'apologie du nazisme, de contestations de l'existence de crimes contre l'humanité, de fausse nouvelle, de même que tout Contenu destiné à exhiber ou vendre des objets et/ou d'ouvrages interdits ; d'atteinte à l'autorité de la justice ; d'informations relatives à l'adoption, au procès, au suicide de mineurs, ou à une situation fiscale individuelle ; de diffusion hors des conditions autorisées de sondages et simulations de vote relatifs à une élection ou un référendum ; de diffamation et injure ; d'atteinte à la vie privée ; ou encore d'acte mettant en péril des mineurs notamment par la fabrication, le transport, et la diffusion de message à caractère violent ou pornographique ou de nature à porter gravement atteinte à la dignité humaine</p><br/>
    <p><b>j)</b> tenter d'induire en erreur d'autres utilisateurs en usurpant le nom ou la dénomination sociale d'autres personnes et plus particulièrement en vous faisant passer pour un employé ou un affilié de <b>Ilay NOSY</b>, un modérateur, un guide, ou un hébergeur; contrefaire des en-têtes ou manipuler de toute autre manière l'identifiant de manière à dissimuler l'origine du Contenu transmis via le Service</p>
    <br/>
    <p><b>k)</b> télécharger, afficher, transmettre par e-mail ou de toute autre manière tout Contenu que vous n'auriez pas le droit de diffuser par une mesure législative ou un acte juridique (notamment des informations internes, privilégiées, confidentielles apprises ou divulguées dans le cadre d'un contrat de travail ou d'un accord de confidentialité sans que cette énumération ne soit limitative)</p><br/>
    <p><b>l)</b> télécharger, afficher, transmettre par e-mail ou de toute autre manière tout Contenu violant tout brevet, marque déposée, secret de fabrication, droit de propriété intellectuelle ou tout autre droit de propriété (ci-après dénommés collectivement les « Droits ») appartenant à autrui</p><br/>
    <p><b>m)</b> télécharger, afficher, transmettre par e-mail ou de toute autre manière toute publicité ou tout matériel promotionnel non sollicités ou non autorisés (notamment se livrer à du « spam », à la transmission de « junk mail », de chaîne de lettres ou toute autre forme de sollicitation) </p>
    <br/>
    <p><b>n)</b> télécharger, afficher, transmettre par e-mail ou de toute autre manière tout Contenu comprenant des virus informatiques ou tout autre code, dossier ou programme conçus pour interrompre, détruire ou limiter la fonctionnalité de tout logiciel, ordinateur, ou outil de télécommunication sans que cette énumération ne soit limitative</p><br/>
    <p><b>o)</b> perturber le flux normal des dialogues, accélérer le rythme de défilement de l'écran de telle manière que les utilisateurs du Service se trouvent dans l'impossibilité de suivre et de taper leur dialogue ou commettre toute autre action ayant un effet perturbateur similaire entravant la capacité des utilisateurs de communiquer en temps réel</p><br/>
    <p><b>p)</b> entraver ou perturber le Service, les serveurs, les réseaux connectés au Service, ou refuser de se conformer aux conditions requises, aux procédures, aux règles générales ou aux dispositions réglementaires applicables aux réseaux connectés au Service</p><br/>
    <p><b>q)</b> violer, intentionnellement ou non, toute loi ou réglementation nationale ou internationale en vigueur.</p>
    <br/>
    <p><b>r)</b> harceler de quelque manière que ce soit un autre ou plusieurs autres utilisateurs</p><br/>
    <p><b>s)</b> collecter et stocker des données personnelles afférentes aux autres utilisateurs</p><br/>
    <p><b>t)</b> de mettre en ligne des annonces ayant un rapport avec des : <br/>
    actions et autres valeurs mobilières ; activités dangereuses (par exemple, tir à l'arme à feu), armes et objets s'y rapportant telles qu'armes à feu, pièces détachées d'armes à feu et chargeurs, munitions, pistolets à plomb et à billes, gaz lacrymogène, pistolets hypodermiques, couteaux à cran d'arrêt, et armes destinées aux arts martiaux ; annonces de mineur de moins de 18 ans ; annonces propositions ou offres de photos ou vidéos privées ; annonces type commercial par particulier : vente grosse quantité, élevage d'animaux, agence immobilière, etc... ; billets de loterie et machines à sous ; caractère religieux ; chaînes d'argent ou tout type de multi-level marketing ; comportements insultants, discriminatoires, offensants ou violents ; contenus offensants, notamment propagande néo-nazie et toute forme d'incitation à la haine raciale ; contrefaçons ; copies non autorisées ; décodeurs (hard- et software) pour médias à accès protégé comme satellite et TV ; demandes d'argent ; drogues et matériels s'y rapportant ; enregistrements pirates ; équipements de démolition et explosifs ; fausses monnaies et faux timbres ; feux d'artifice ; importations d'animaux sans tatouage ou certificat de vaccination ou lof ; impressions d'images provenant de films ; incitations à l'émeute ; incitations au meurtre ou à la violence ; informations financières personnelles et informations personnelles (quelle qu'en soit la forme, y compris les listes de distribution) ; insignes et uniformes de police ou autres insignes et uniformes officiels ; jeux de hasard ; matériaux destinés à l'ouverture des serrures ; objets de pédo-pornographie ou dangereux pour la morale des jeunes ; objets volés ; papiers d'identité ; particuliers vendant services intermédiaires contacts, même pour locations, et boîte aux lettres ; pesticides ; produits de type médical ; produits sanguins, fluides corporels et organes ; profits en utilisant un nom célèbre ; proposition de gains non précisés sur web, loto, etc... ; pyramides financières ;  recrutements de secte ; services à caractère médical, opérations de toutes sortes, trafic d'organes ; usages de marques non autorisés ; vendus par un particulier (photocopie obligatoire des cartes grises au nom du vendeur, au delà du 3ème véhicule) ; ventes de renseignements, adresses<br/>
    Cette liste n'est pas exhaustive et peut être modifiée à tout moment par le directeur de la publication de <b>Ilay NOSY</b>.com</p><br/>
    <p><b>u)</b> règles spécifiques liées aux rubriques :<br/>
      <b>Véhicules</b> : Si vous souhaitez diffuser une annonce proposant la vente d'un véhicule (un seul véhicule par annonce), vous devez respecter certaines règles.  Voici les informations obligatoires que le véhicule soit neuf ou d'occasion : la marque du véhicule, le type (berline, coupé...), le modèle, et si nécessaire la variante de ce modèle. La variante est désignée par une appellation unique qui doit permettre d'identifier les véhicules d'un même modèle de la marque présentant des caractéristiques techniques homogènes de motorisation, de transmission, de carrosserie, ainsi que d'équipements substantiels de sécurité, de confort et d'aménagement intérieur. L'information doit donc permettre d'identifier très précisément le véhicule sans qu'aucune confusion ne soit possible pour l'éventuel acheteur.<br/>
    Concernant plus particulièrement les voitures neuves, il est obligatoire d'indiquer dans les publicités les informations suivantes : la consommation de carburant, les émissions de dioxyde de carbone. <br/>
        Lorsque le véhicule proposé à la vente est d'occasion, votre annonce doit contenir en plus les informations suivantes : le mois et de l'année de la première mise en circulation, l'indication du kilométrage total parcouru depuis cette mise en circulation, s'il s'agit d'un véhicule acquis neuf par le vendeur (première main), si le kilométrage réel peut être justifié par le vendeur. Si vous ne pouvez pas garantir l'indication du kilométrage total parcouru, vous devez indiquer le kilométrage inscrit au compteur suivi de la mention « non garanti ».<br/>
      <b>équipement auto</b> : Seule la diffusion d'annonces proposant la vente de produits originaux est autorisée. La vente de copie est considérée par les Tribunaux comme de la contrefaçon.<br/>
        <b>Annonces immobilières</b> : Si vous diffusez une annonce en qualité de professionnel de l'immobilier (agences immobilières, notaires, marchands de liste...) vous devez, pour que cette dernière soit légale, mentionner obligatoirement le montant toutes taxes comprises (T.T.C.) de votre rémunération lorsqu'elle est à la charge du locataire ou de l'acquéreur, et qu'elle n'est pas incluse dans le prix annoncé. Si votre rémunération est comprise dans le prix affiché, votre annonce doit indiquer « frais d'agence inclus », ou « honoraires inclus ».<br/>
    <b>Offres de location</b> : si votre annonce comporte un élément chiffré (montant du loyer), vous devez indiquer le montant de votre rémunération correspondant à cette location (exemple : frais d'agence 5% du loyer annuel hors charges). Une annonce pour l'acquisition d'un bien immobilier prévoyant la possibilité d'obtenir un prêt pour financer cet achat est soumis à des règles particulières. L'annonce doit comporter les mentions obligatoires. Le document doit obligatoirement contenir toutes les mentions nécessaires à l'information du lecteur de l'annonce et notamment : préciser l'identité du prêteur, la nature et l'objet du prêt ; préciser, si elle comporte un ou plusieurs éléments chiffrés, la durée de l'opération proposée ainsi que le coût total et le taux effectif global annuel du crédit, à l'exclusion de tout autre taux. Toutes les mentions obligatoires doivent être présentées de manière parfaitement lisible et compréhensible par le lecteur. Les petites annonces ne comportant que le montant du crédit à payer mensuellement sont interdites (exemple : votre villa pour 500 000 Ar par mois). Il est également interdit d'assimiler un remboursement de crédit à un loyer.<br/>
      <b>Informatique, Téléphonie, Image & Son, Vêtements & Accessoires, Jeux vidéo, DVD / Films, CD / Musique</b> : Seule la diffusion d'annonces proposant la vente d'exemplaires originaux est autorisée. La vente de copie est considérée par les Tribunaux comme de la contrefaçon qui peut être sanctionnée.<br/>
      <b>Livres</b> : Si vous diffusez une annonce en qualité de professionnel du livre, vous ne pouvez pas effectuer de remises supérieures à 5% du prix fixé par l'éditeur ou l'importateur.<br/>
        <b>Emploi</b> : votre annonce doit être rédigée dans le respect des principes suivants. La bonne compréhension : l'annonce doit être écrite en français ou malgache. Lorsqu'un terme étranger ne peut trouver son équivalent en français, il doit être circonscrit d'une manière assez précise pour ne pas induire en erreur le lecteur. L'annonce ne doit pas comporter des allégations fausses ou susceptibles d'induire le lecteur en erreur. L'exactitude des mentions relatives à l'existence, l'origine, la nature, la description de l'emploi ou du travail à domicile, de même de la rémunération, des avantages annexes proposés ainsi que le lieu de travail doit être particulièrement vérifiée. Les mentions interdites : il est interdit d'indiquer des limites d'âge maximales, des dispositions discriminatoires ou sexistes en particulier. Mais rien n'empêche de mentionner un âge minimal dans certains cas : les emplois qui ne peuvent légalement être exercés en dessous d'un certain âge, comme les jeunes employés dans les débits de boissons et certains travaux dangereux, les emplois que l'entreprise estime ne pas pouvoir confier à un salarié trop jeune. L'interdiction des dispositions discriminatoires. Lorsque l'offre et l'annonce correspondante concernent un emploi dont il existe une dénomination au masculin et au féminin (par exemple : employé/e) de mentionner les 2 genres. Lorsque la dénomination de l'emploi n'existe qu'au masculin, ou qu'au féminin il faut rajouter une mention qui indique que l'emploi est offert aux candidats des 2 sexes (H/F) ou utiliser des mots neutres, tel que personnel/le, chargé/e de..., lorsqu'il résulte clairement de la rédaction de l'offre qu'elle est adressée aux candidats des 2 sexes, dans des conditions identiques.<br/>
        <b>La gratuité de l'annonce</b> : les offres d'emploi ne peuvent pas demander à une personne d'envoyer une somme d'argent pour avoir accès à une offre d'emploi. Cette pratique est illégale.<br/>
        <b>Services</b> : Lorsque l'offre de service est diffusée par un particulier à l'attention d'un particulier, elle doit indiquer la rémunération et uniquement pour les activités suivantes : Entretien de la maison et travaux ménagers ; Petits travaux de jardinage ; Prestations de petit bricolage dites « hommes toutes mains » ; Garde d'enfant à domicile ; Soutien scolaire et cours à domicile ; Préparation de repas à domicile, y compris le temps passé aux commissions ; Livraison de repas à domicile, à la condition que cette prestation soit comprise dans une offre de services incluant un ensemble d'activités effectuées à domicile ; Collecte et livraison à domicile de linge repassé, à la condition que cette prestation soit comprise dans une offre de services incluant un ensemble d'activités effectuées à domicile ; Assistance aux personnes âgées ou autres personnes qui ont besoin d'une aide personnelle à leur domicile, à l'exception d'actes de soins relevant d'actes médicaux ; Assistance aux personnes handicapées, y compris les activités d'interprète en langue des signes, de technicien de l'écrit et de codeur en langage parlé complété ; Garde-malade, à l'exclusion des soins ; Aide à la mobilité et transports de personnes ayant des difficultés de déplacement lorsque cette activité est incluse dans une offre de services d'assistance à domicile ; Prestation de conduite du véhicule personnel des personnes dépendantes, du domicile au travail, sur le lieu de vacances, pour les démarches administratives, à la condition que cette prestation soit comprise dans une offre de services incluant un ensemble d'activités effectuées à domicile ; Accompagnement des personnes âgées ou handicapées en dehors de leur domicile (promenades, transports, actes de la vie courante), à condition que cette prestation soit comprise dans une offre de services incluant un ensemble d'activités effectuées à domicile ; Livraison de courses à domicile, à la condition que cette prestation soit comprise dans une offre de services comprenant un ensemble d'activités effectuées à domicile ; Assistance informatique et Internet à domicile  ; Soins et promenades d'animaux domestiques, pour les personnes dépendantes ; Soins d'esthétique à domicile pour les personnes dépendantes ; Gardiennage et surveillance temporaire, à domicile, de la résidence principale et secondaire ; Assistance administrative à domicile. Pour toutes les autres offres de services (peinture, plomberie...). Exemples : « Particulier propose soins et promenade d'animaux domestiques Tél. : XX.XX.XX.XX.XX... ». « Particulier propose travaux de peinture chez particulier. Tél. : XX.XX.XX.XX.XX.  ». Si vous diffusez votre annonce en qualité d'artisans ou de dépanneurs, cette dernière doit indiquer les informations suivantes : le nom, la raison sociale et l'adresse de l'entreprise, le numéro de STAT - NIF - RCS, les taux horaires de main-d'oeuvre toutes taxes comprises pratiqués pour 
égorie de prestation concernée ou les prix unitaires, quelles que soient les unités, les frais de déplacement, lorsque les entreprises se rendent au domicile du consommateur, le caractère payant ou non du devis, le cas échéant, toute autre condition de rémunération des prestataires. Les prestations concernées par ces mentions obligatoires sont les prestations d'entretien, dépannage, réparations effectuées pour les travaux suivants : maçonnerie, fumisterie et génie climatiques à l'exception des opérations exécutées dans le cadre de contrats relatifs à l'exploitation de chauffage-climatisation, ramonage, isolation, menuiserie, serrurerie, couverture, plomberie, installation sanitaire, étanchéité, plâtrerie, peinture, vitrerie, miroiterie, revêtement de murs et de sols en tous matériaux, installation électrique.<br/>
        Les opérations de raccordement, d'installation, d'entretien, de réparation ou de réglage portant sur des équipements électriques, électroniques, informatiques, radioélectriques et électroménagers, quel que soit le lieu d'exécution, sont également concernées par ces mentions obligatoires.<br/>
      <br/>
        <b>Cours particuliers</b> : Lorsque l'offre de service est diffusée par un particulier à l'attention d'un particulier, elle doit indiquer la rémunération  effectuée.</p>
    <br/>
    <p>Toute infraction aux règles énoncées ci-dessus vaudra suppression immédiate et irréversible de l'annonce et si nécessaire, procès devant le tribunal du demandeur. De même que toute annonce pas claire, imprécise, avec un vocabulaire confus ou ambigu, trop d'abréviations et/ou inintelligible.</p>
    <p>Vous reconnaissez que <b>Ilay NOSY</b> ne peut visionner le Contenu avant sa diffusion. Néanmoins <b>Ilay NOSY</b>, ou toute personne ou entité désignée par cette société, se réserve le droit, à sa seule discrétion, (sans que cela ne constitue une obligation) de refuser ou de déplacer tout Contenu disponible via le Service. Par ailleurs, <b>Ilay NOSY</b>, ou toute personne ou entité désignée par cette société, sera en droit de supprimer ou de retirer tout Contenu qui violerait les termes des présentes et/ou de la réglementation en vigueur et/ou serait répréhensible de toute autre façon. Vous reconnaissez également que vous devez faire preuve de discernement, et supporter tous les risques y afférant, dans l'utilisation que vous faites du Contenu et notamment lorsque vous vous fiez à l'opportunité, l'utilité ou le caractère complet de ce Contenu. En conséquence, vous reconnaissez que vous ne pouvez vous fier ni au Contenu créé par <b>Ilay NOSY</b> ni au Contenu soumis à <b>Ilay NOSY</b>, notamment disponible dans les Forums ou dans toutes autres parties du Service.</p><br/>
    <p>Vous reconnaissez et acceptez que si <b><b>Ilay NOSY</b></b> protège le Contenu, <b>Ilay NOSY</b> peut être amené à le divulguer pour se conformer aux lois en vigueur ou si de bonne foi, <b>Ilay NOSY</b> pense qu'une telle mesure est nécessaire (i) dans le cadre d'une procédure judiciaire, (ii) pour faire respecter les Conditions d'utilisation du Service, (iii) pour répondre à des plaintes arguant de la violation des droits de tiers, (iv) pour protéger les droits ou les intérêts de <b>Ilay NOSY,</b> ses utilisateurs ou le public.</p><br/>
    <p class="droite"><a class="haut" href="#conditions">haut &uArr;</a></p>
    
    <a name="7"></a>
    <p class="titre"><b>7 - Recommandation particulière aux utilisateurs internationaux</b></p><br/>
    <p>Compte tenu du caractère mondial du réseau Internet, vous acceptez de vous conformer à toutes les règles applicables dans le pays où vous consultez le Contenu et à partir duquel vous émettez du Contenu, au comportement des utilisateurs du réseau et au Contenu admissible. En particulier vous acceptez de vous conformer aux lois applicables en matière de transmission de données à partir de la Madagascar ou du pays où vous résidez.</p><br/>
    <p class="droite"><a class="haut" href="#conditions">haut &uArr;</a></p>
    
    <a name="8"></a>
    <p class="titre"><b>8 - Contenu accessible à tous sur Ilay NOSY</b></p><br/>
    <p><b>a)</b> Pour les besoins des présentes Conditions d'utilisation « les zones du Service accessibles à tous » sont les zones ouvertes à tous les utilisateurs des Services quels qu'ils soient. Par exemple, une zone du Service accessible à tous inclut la partie publique du forum de <b>Ilay NOSY</b>.</p><br/>
    <p><b>b)</b> Pour ce qui concerne le Contenu que vous décidez d'envoyer pour être inclus dans des zones accessibles à tous, ainsi que le Contenu composé de photos ou d'images et que vous décidez de diffuser ou d'envoyer dans des zones accessibles à tous du Service, vous accordez à <b>Ilay NOSY</b>, pour le monde, une licence non-exclusive et gracieuse permettant à <b>Ilay NOSY</b> de reproduire, publier et diffuser ce Contenu sur le Service et ce exclusivement en vue de promouvoir la section de <b>Ilay NOSY</b>. Ce Contenu aura été envoyé et diffusé ou, pour ce qui concerne les photos et les images, en respectant la raison pour laquelle cette photo ou cette image a été soumise au Service. Cette licence sera accordée pour la durée pendant laquelle vous déciderez d'inclure le Contenu sur le Service et se terminera automatiquement dès que vous aurez retiré le Contenu du Service. Vous garantissez avoir préalablement obtenu les droits nécessaires à cette exploitation. ce contenu pourra être repris par des partenaires de Ilay NOSY à sa seule discrétion dans le but d'en faire la promotion.</p><br/>
    <p><b>c)</b> Pour ce qui concerne tout autre Contenu que vous décidez d'envoyer dans toute autre zone accessible à tous du Service, vous accordez à <b>Ilay NOSY</b>, pour le monde et pour la durée des droits d'auteurs, une licence non-exclusive et gracieuse permettant à <b>Ilay NOSY</b> de reproduire, distribuer, publier, sous-licencier, diffuser tout ou partie de ce Contenu, et vous reconnaissez également que <b>Ilay NOSY</b> est libre d'inclure le Contenu dans toute autre oeuvre et ce pour une diffusion par tous moyens connus ou à découvrir. Vous garantissez avoir préalablement obtenu les droits nécessaires à cette exploitation.</p><br/>
    <p><b>d)</b> Certaines  informations, indications ou contenus (photographie ou vidéo) que les Membres  peuvent fournir à titre facultatif sont susceptibles, sous la responsabilité du  Membre concerné, de révéler l'origine ethnique du Membre, sa nationalité, sa  religion et/ou ses orientations sexuelles. En fournissant de telles  informations, toutes facultatives, le Membre concerné manifeste son souhait et,  par conséquent, son consentement explicite au traitement de ces données dites "sensibles" par Ilay NOSY et en prend librement la responsabilité  exclusive.</p><br/>
    <p class="droite"><a class="haut" href="#conditions">haut &uArr;</a></p>
    
    <a name="9"></a>
    <p class="titre"><b>9 - Indemnisation</b></p><br/>
    <p>Vous vous engagez à garantir et indemniser Ilay NOSY, ainsi que ses sociétés soeurs ou affiliées, ses représentants, ses salariés, ses partenaires, contre tout dommage, plainte ou demande émanant de tiers consécutif à l'envoi, l'affichage, le téléchargement, la diffusion ou la transmission de Contenu par vous sur le Service, à l'utilisation du Service, à la violation des Conditions d'utilisation, ou des droits d'autrui ou de l'ordre public. Cette garantie couvrant tant les indemnités qui seraient éventuellement versées que les honoraires d'avocat et frais de justice dans une limite raisonnable.</p><br/>
    <p class="droite"><a class="haut" href="#conditions">haut &uArr;</a></p>

    <a name="10"></a>
    <p class="titre"><b>10 - Interdiction de revendre le service</b></p><br/>
    <p>Vous vous interdisez de reproduire, copier, vendre, revendre, ou exploiter dans un but commercial quel qu'il soit toute partie du Service, toute utilisation du Service, ou tout droit d'accès au Service.</p><br/>
    <p class="droite"><a class="haut" href="#conditions">haut &uArr;</a></p>
    
    <a name="11"></a>
    <p class="titre"><b>11 - Règles générales en matière d'utilisation et de stockage</b></p><br/>
    <p>Vous reconnaissez que <b>Ilay NOSY</b> peut poser des règles générales et des limites quant à l'utilisation du Service, et notamment, sans que cette énumération soit limitative, fixer un nombre de jours maximum pendant lesquels les messages e-mail, les messages affichés dans les Forums, ou tout autre Contenu téléchargé seront conservés, fixer un nombre maximum de e-mails qui pourront être envoyés et reçus par un compte sur le Service, fixer une taille maximale aux e-mails qui peuvent être envoyés et reçus par un compte sur le Service, fixer un espace de mémoire maximum qui vous sera alloué  sur les serveurs de <b>Ilay NOSY</b> et fixer un maximum au nombre de fois où vous pouvez accéder à un Service pendant une période donnée (ainsi que la durée maximale de chaque accès). Vous reconnaissez que <b>Ilay NOSY</b> n'apporte aucune garantie pour la suppression ou le défaut de stockage de tout message, de toute communication ou de tout autre Contenu diffusé ou transmis via le Service. Vous reconnaissez également que <b>Ilay NOSY</b> sera libre de supprimer tout compte resté inutilisé pendant un certain temps et que <b>Ilay NOSY</b> est libre de modifier les présentes règles générales à tout moment, c'est pourquoi <b>Ilay NOSY</b> vous recommande de vous y référer régulièrement.</p><br/>
    <p class="droite"><a class="haut" href="#conditions">haut &uArr;</a></p>
    
    <a name="12"></a>
    <p class="titre"><b>12 - Modification de service</b></p><br/>
    <p><b>Ilay NOSY</b> se réserve le droit, à tout moment, de modifier interrompre temporairement ou de manière permanente tout ou partie du Service et ce sans avoir à vous en informer préalablement. Ilay NOSY ne pourra être tenu responsable à votre encontre ou à l'encontre de tout tiers pour toute modification, suspension ou interruption du Service.</p><br/>
    <p class="droite"><a class="haut" href="#conditions">haut &uArr;</a></p>
    
    <a name="13"></a>
    <p class="titre"><b>13 - Résiliation</b></p><br/>
    <p>Vous reconnaissez à <b>Ilay NOSY</b> le droit de mettre fin à tout ou  partie du droit d'accès correspondant à votre compte et votre mot de passe,  voire de supprimer votre compte et mot de passe, ainsi que le droit de retirer  ou de déplacer tout Contenu sur le Service et ce pour tout motif notamment en  raison de l'absence d'utilisation, ou si <b>Ilay NOSY</b> a de bonnes raisons de croire que vous avez violé ou agi en contradiction avec  la lettre ou l'esprit des présentes Conditions d'utilisation. <b>Ilay NOSY</b> peut également unilatéralement  et à tout moment interrompre la fourniture du Service. Vous reconnaissez que  toute résiliation de votre accès au Service en application des termes des  présentes peut intervenir sans mise en demeure préalable, et vous reconnaissez et  acceptez que <b>Ilay NOSY</b> sera en droit de  désactiver ou supprimer à tout moment et avec effet immédiat votre compte et  tout dossier ou fichier présent dans ce compte et/ou interdire tout accès  ultérieur à ces fichiers ou au Service. De plus vous reconnaissez que <b>Ilay NOSY</b> ne pourra être tenu pour  responsable à votre encontre ou à l'encontre de tiers pour toute résiliation de  votre accès au Service.</p><br/>
    <p class="droite"><a class="haut" href="#conditions">haut &uArr;</a></p>
    
    <a name="14"></a>
    <p class="titre"><b>14 - Relation avec les annonceurs</b></p><br/>
    <p>Vos correspondances, votre relation commerciale avec des annonceurs, ou votre participation à des  promotions organisées par des annonceurs trouvés par ou sur le Service y  compris le paiement et la livraison de biens ou service, ou tous autres termes,  conditions, garanties ou déclarations en relation avec ces opérations se fait  directement entre vous et l'annonceur. En conséquence, vous reconnaissez que <b>Ilay NOSY</b> ne peut être tenu pour  responsable de toute perte ou de tout dommage quelqu'il soit consécutif à cette  relation ou plus largement à la présence d'annonceur sur le Service.</p><br/>
    <p class="droite"><a class="haut" href="#conditions">haut &uArr;</a></p>
    
    <a name="15"></a>
    <p class="titre"><b>15 - Liens</b></p><br/>
    <p>Le Service peut  fournir ou des tiers peuvent inclure des liens vers d'autres sites Web ou  d'autres sources Internet. Dans la mesure où <b>Ilay NOSY</b> ne peut contrôler ces sites et ces sources externes, vous  reconnaissez que <b>Ilay NOSY</b> ne peut être  tenu pour responsable de la mise à disposition de ces sites et sources  externes, et ne peut supporter aucune responsabilité quant au Contenu,  publicités, produits, services ou tout autre matériel disponible sur ou à  partir de ces sites ou sources externes. De plus, vous reconnaissez que <b>Ilay NOSY</b> ne pourra être tenu responsable  de tous dommages ou pertes avérés ou allégués consécutifs ou en relation avec  l'utilisation ou avec le fait d'avoir fait confiance au Contenu, à des biens ou  des services disponibles sur ces sites ou sources externes.</p>
    <p>Enfin, si dans le cadre  d'une recherche conduite sur www.<b>Ilay NOSY</b>.com  à partir d'une arborescence, de mots clefs, le résultat de celle-ci vous  amenait à pointer sur des sites, des pages ou des forums dont le titre et/ou  les contenus constituent une infraction à la loi malgache, compte tenu  notamment du fait que <b>Ilay NOSY</b> ne  saurait contrôler le Contenu de ces sites et sources externes (y compris les  Contenus référencés sur les autres Sites et Services de <b>Ilay NOSY</b> dans le monde), vous devez interrompre votre consultation du  site concerné sauf à encourir les sanctions prévues par la législation  malgache ou à répondre des actions en justice initiées à votre encontre.</p><br/>
    <p class="droite"><a class="haut" href="#conditions">haut &uArr;</a></p>
    
    <a name="16"></a>
    <p class="titre"><b>16 - Droit de propriété de Ilay NOSY</b></p><br/>
    <p>Vous reconnaissez et  acceptez que le Service et tout logiciel utilisé nécessairement en relation  avec le Service (ci-après dénommés « Logiciels ») peuvent contenir  des informations confidentielles et protégées par le droit de propriété  intellectuelle en vigueur ou toute autre loi. Vous reconnaissez également avoir  connaissance que les informations qui vous sont présentées via le Service ou  par des annonceurs sont protégés par le droit d'auteur, le droit des marques,  le droit des brevets, ou tout autre droit reconnu par la législation en  vigueur. Sauf expressément autorisé à cet effet par <b>Ilay NOSY</b> ou par l'annonceur, vous vous engagez à ne pas modifier,  louer, emprunter, vendre, distribuer ou créer d'oeuvres dérivées basées en tout  ou partie sur le Service, ou les Logiciels.</p>
    <p><b>Ilay NOSY</b> vous accorde, à titre personnel, le droit non exclusif et non  cessible d'utiliser les Logiciels sur un seul ordinateur ; étant précisé  qu'il vous est interdit (et que vous ne pouvez accorder à autrui  l'autorisation) de copier, modifier, créer une oeuvre dérivée, inverser la conception  ou l'assemblage ou de toute autre manière tenter de trouver le code source (à  l'exception des cas prévus par la loi), vendre, attribuer, sous-licencier ou  transférer de quelque manière que se soit tout droit afférent aux Logiciels.  Vous vous engagez à ne modifier en aucune manière le Logiciel ou à ne pas  utiliser de versions modifiées des Logiciels et notamment (sans que cette  énumération soit limitative) en vue d'obtenir un accès non autorisé au Service.  Vous acceptez de ne pas accéder au Service par un autre moyen que par  l'interface qui vous est fournie par <b>Ilay NOSY</b> à cet effet.</p><br/>
    <p class="droite"><a class="haut" href="#conditions">haut &uArr;</a></p>
    
    <a name="17"></a>
    <p class="titre"><b>17 - Garanties</b></p><br/>
    <p>Vous reconnaissez et  acceptez expressément que :</p>
    <ul>
        <li>VOTRE UTILISATION DU SERVICE SE  FAIT A VOS RISQUES ET PERILS. LE SERVICE VOUS EST FOURNI SUR LA BASE D'UN SERVICE « EN L'ETAT » ET ACCESSIBLE EN FONCTION DE SA DISPONIBILITE. <b>ILAY NOSY</b> NE FOURNIT AUCUNE GARANTIE  EXPRESSE OU IMPLICITE, EN CE Y COMPRIS SANS QUE CETTE ENUMERATION NE SOIT  LIMITATIVE LES GARANTIES AFFERENTES A LA QUALITE ET LA COMPATIBILITE DU  SERVICE A UN USAGE SPECIFIQUE, ET A LA NON VIOLATION DES REGLES D'UTILISATION DU SERVICE  PAR SES UTILISATEURS.</li>
        <li><b>ILAY NOSY</b> NE GARANTIT PAS QUE (i) LE SERVICE REPONDRA PARFAITEMENT A VOS ATTENTES  (ii) LE SERVICE SERA ININTERROMPU, OPPORTUN, SUR OU DEPOURVU DE TOUTE ERREUR  (iii) LES RESULTATS QUI PEUVENT ETRE OBTENU EN UTILISANT LE SERVICE SERONT  EXACTS ET FIABLES (iv) LA QUALITE DE TOUS PRODUITS, SERVICES, INFORMATIONS OU TOUT AUTRE MATERIEL ACHETES OU OBTENUS PAR VOUS SUR LE SERVICE SERONT A LA HAUTEUR DE VOS  ATTENTES, ET (v) QUE LES DEFAUTS DANS LES LOGICIELS UTILISES, S'IL EN  EXISTE, FERONT L'OBJET D'UNE CORRECTION.</li>
        <li>TOUS MATERIELS TELECHARGES OU  OBTENUS DE TOUTE AUTRE MANIERE LORS DE L'UTILISATION DU SERVICE A VOS RISQUES  ET PERILS. VOUS SEREZ SEUL RESPONSABLE POUR TOUT DOMMAGE SUBI PAR VOTRE  ORDINATEUR OU TOUTE PERTE DE DONNEES CONSECUTIFS AU TELECHARGEMENT DE CE  MATERIEL.</li>
        <li>AUCUN CONSEIL ET AUCUNE  INFORMATION, QU'ILS SOIENT ORAUX OU ECRITS, OBTENUS PAR VOUS DE ILAY NOSY OU LORS  DE L'UTILISATION DU SERVICE NE SONT SUSCEPTIBLES DE CREER DES GARANTIES NON  EXPRESSEMENT PREVUES PAR LE PRESENT ACCORD.</li>
    </ul><br/>
    <p class="droite"><a class="haut" href="#conditions">haut &uArr;</a></p>
    
    <a name="18"></a>
    <p class="titre"><b>18 - Limitation de responsabilité</b></p><br/>
    <p>VOUS RECONNAISSEZ ET  ACCEPTEZ QUE, DANS TOUTE LA MESURE PERMISE PAR LA REGLEMENTATION EN  VIGUEUR, <b>ILAY NOSY</b> NE POURRA ETRE TENU  POUR RESPONSABLE DE TOUT DOMMAGE DIRECT OU INDIRECT EN CE Y COMPRIS NOTAMMENT  LES PERTES DE PROFITS, DE CLIENTELE, DE DONNEES OU TOUTE AUTRE PERTE DE BIENS  INCORPORELS (ET CE MEME SI ILAY NOSY A ETE INFORME DE LA POTENTIALITE DE  TELS DOMMAGES) POUVANT SURVENIR (i) DE L''UTILISATION OU AU CONTRAIRE DE  L'IMPOSSIBILITE D'UTILISER LE SERVICE, (ii) DE COUT POUVANT SURVENIR DU  FAIT DE L'AQUISITION DE BIENS OU DE SERVICES DE SUBSTITUTION RESULTANT DE  L'ACHAT DE BIENS OU DE SERVICES OU A LA RECEPTION DE MESSAGES OU A DES TRANSACTIONS SURVENUES  LORS DE L'UTILISATION DU SERVICE, (iii) SUITE A UN ACCES NON AUTORISE AU  SERVICE PAR UN UTILISATEUR OU A LA MODIFICATION DE VOTRE TRANSMISSION OU DE VOTRE  BANQUE DE DONNEES ; (iv) SUITE A UNE DECLARATION OU A LA CONDUITE D'UN TIERS  SUR LE SERVICE ET (v) TOUTES AUTRES QUESTIONS EN RAPPORT AVEC LE SERVICE.</p><br/>
    <p class="droite"><a class="haut" href="#conditions">haut &uArr;</a></p>
    
    <a name="19"></a>
    <p class="titre"><b>19 - Avertissement spécifique pour les services concernant les questions financières</b></p><br/>
    <p>Dans l'hypothèse où  vous auriez l'intention de créer ou d'utiliser tout service, de recevoir ou de  demander des actualités, des messages, des alertes, ou toutes informations via  le Service et concernant des sociétés, des  investissements, ou des titres, relisez les paragraphes 17 et 18 ci-dessus car  ils s'appliquent doublement à vous. De plus, pour ce type d'information, le mot  d'ordre doit être « Méfiez-vous des conseils d'investissements ». Le  Service vous est fourni dans un but d'information exclusivement, et aucun  Contenu diffusé sur le Service n'est destiné à être utilisé pour effectuer des  transactions ou de prendre des décisions d'investissement. <b>Ilay NOSY</b> ne peut être tenu responsable du contenu ou de l'exactitude  de tout ou partie des informations transmises via le Service, pas plus que <b>Ilay NOSY</b> ne pourra être tenu responsable  de tout ordre ou décision d'investissement basés sur de telles informations.</p>
    <br/>
    <p class="droite"><a class="haut" href="#conditions">haut &uArr;</a></p>
    
    <a name="20"></a>
    <p class="titre"><b>20 - Notification</b></p><br/>
    <p>Toute notification  pourra vous être adressée par e-mail ou par courrier postal. <b>Ilay NOSY</b> se réserve également la  possibilité de modifier les présentes Conditions d'utilisation du Service en  plaçant directement sur le Service des notifications de changement ou des liens  vers de telles notifications.</p><br/>
    <p class="droite"><a class="haut" href="#conditions">haut &uArr;</a></p>
    
    <a name="21"></a>
    <p class="titre"><b>21 - Informations afférentes aux marques déposées</b></p><br/>
    <p>Le terme <b>Ilay NOSY</b> est une marques déposée et  dûment protégée. L'Utilisateur Final s'engage expressément à respecter les  droits des titulaires des droits d'auteur sur ces marques et plus  particulièrement à ne pas utiliser de quelque manière que ce soit ladite  marque. Notamment toute utilisation frauduleuse ou contrefaçon engagerait la  responsabilité civile et pénale de l'Utilisateur Final.Sans autorisation  expresse de <b>Ilay NOSY</b>, vous vous  engagez à ne pas utiliser ou diffuser de quelque manière que se soit les  Marques <b>Ilay NOSY</b>.</p><br/>
    <p class="droite"><a class="haut" href="#conditions">haut &uArr;</a></p>
    
    <a name="22"></a>
    <p class="titre"><b>22 - Droits de propriété intellectuelle</b></p><br/>
    <p><b>Ilay NOSY</b> respecte les droits de propriété intellectuelle d'autrui et demande à  ses utilisateurs d'en faire autant. Si vous avez de bonnes raisons de croire  que votre oeuvre a été copiée ou est utilisée d'une manière susceptible de  porter atteinte à vos droits tels que reconnus par la législation malgache en  vigueur, merci d'en informer <b>Ilay NOSY</b>  en nous fournissant les informations suivantes :</p>
    <br/>
    <ul>
        <li>la signature électronique ou « physique » de la personne habilitée à agir pour le compte du  titulaire de droits ;</li>
        <li>une description de l'oeuvre que  vous considérez comme ayant été violée ;</li>
        <li>la localisation sur le site du  matériel litigieux ;</li>
        <li>votre adresse, numéro de téléphone  et adresse e-mail ;</li>
        <li>une déclaration sur l'honneur dans  laquelle vous reconnaissez n'avoir pas connaissance que l'utilisation a été  autorisée par le titulaire de droit ou son représentant ;</li>
        <li>une déclaration sur l'honneur,  susceptible d'entraîner des pénalités et des poursuites pour parjure,  reconnaissant que les informations correspondant aux points listés ci-dessus  sont exactes et que vous êtes le titulaire de droit ou habilité à représenter  ce dernier.</li>
    </ul>
    <p>Les coordonnées de <b>Ilay NOSY</b> sont les suivantes :</p><br/>
    <p class="centrer"><b>Société Ilay NOSY SARL<br/>
     Agence de publici&eacute; &amp; R&eacute;gie publicitaire de m&eacute;dias</b><br/> 
    Lot VA 26 K Pr&egrave;s Tsiadana<br/>  
    101 Antananarivo - Madagascar<br />
	url : <a href="http://www.dword-consulting.com" target="_blank">http://www.dword-consulting.com</a><br />
    </p><br/>
    <p class="droite"><a class="haut" href="#conditions">haut &uArr;</a></p>
    
    <a name="23"></a>
    <p class="titre"><b>23 - Divers</b></p><br/>
    <p>Les présentes Conditions d'utilisation du Service constituent la totalité de l'accord passé entre <b>Ilay NOSY</b> et l'utilisateur du  Service pour ce qui concerne l'utilisation du Service, et se substituent à tout  accord éventuellement intervenu antérieurement entre vous et <b>Ilay NOSY</b> Vous pouvez également être  soumis à des conditions d'utilisations additionnelles spécifiques à certains  services, contenus de tiers et logiciels de tiers et qui vous seront  communiquées lorsque vous accédez à ces services, contenus ou logiciels. Le  défaut pour <b>Ilay NOSY</b> d'exercer les  droits qui lui sont reconnus en application des présentes ne constitue pas une  renonciation à faire valoir ces droits. Dans l'hypothèse où l'une quelconque  des dispositions des présentes Conditions d'utilisation serait annulée par une  décision de justice, les parties s'accordent à guider le juge pour que  l'appréciation du juge tienne compte de la commune intention des parties  manifestée par les présentes Conditions d'utilisation, les autres dispositions  demeurant valables et continuant de s'appliquer entre les parties. Les titres  des articles n'ont qu'une valeur indicative.</p>
    <p>Les présentes Conditions  d'utilisation et la relation entre <b>Ilay NOSY</b> et les utilisateurs seront soumises au droit français et tout différend n'ayant  pu trouver une issue transactionnelle sera porté devant les tribunaux  compétents de Paris.</p><br/>
    <p class="droite"><a class="haut" href="#conditions">haut &uArr;</a></p>
    
    <a name="24"></a>
    <p class="titre"><b>24 - Informations suppl&eacute;mentaires</b></p>
    <br/><br/>
    <p>Ilay NOSY est un service de Ilay NOSY SARL</p><br/>
    
    <p><b>Soci&eacute;t&eacute; Ilay NOSY SARL</b><br/>
    Agence de publici&eacute; &amp; R&eacute;gie publicitaire de m&eacute;dias</b><br/> 
    <u>Registre du Commerce et des sociétés</u> : TNR 2011 B 00050<br />
    <u>Statistiques</u> : 74310 11 2011 0 10049<br />
    <u>Num&eacute;ro d'idenfication fiscale</u> : 4000036944<br />
    
    </p>
    <p><a class="haut" href="#conditions">haut &uArr;</a></p>
    <br/>
    <a name="vieprivee"></a>
</div>
                                  
                                        <div class="">
										<table class="commAnnonce expanded" cellspacing="0"  id="tableListeAnnonce">
                                            <tbody>
                                                <tr>
                                                    <td colspan="6">
                                                        <div class="commFoot">
                                                            <div class="static">
                                                                <p class="regTextPale cultureFoot">&nbsp;</p>
                                                            </div>
                                                            <div class="commFoot3">
                                                            </div>
                                                        </div>                                                                                                                                              
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                        </div>
									</div>