                            <div class="row" id="reelFilNews">
	                            <div class="header">
                                	<h3>Flash &eacute;vènement du jour : vend 12 novembre 2010 </h3>
                                </div><!-- header:[end] -->
                                <div class="singleColumnBig">                                
                                    <ul class="list">
                                        <li><span class="heure">&raquo; 18h17</span> <span class="titre">Cooliris est sûrement le plugin qui vous manquait. Transformez votre navigateur internet pour visualiser les images et les vid&eacute;os en 3D</span></li>
                                        <li><span class="heure">&raquo; 18h15</span> <span class="titre">Deux avions de la S&eacute;curit&eacute; civile transportant chacun dix personnes ont d&eacute;coll&eacute; vers 10h30, un troisième avion transportant quarante personnes a d&eacute;coll&eacute; peu après.«Ils seront r&eacute;partis sur un ensemble de centres de r&eacute;tention dans le Sud où les familles</span></li>
                                        <li><span class="heure">&raquo; 17h17</span> <span class="titre">Cooliris est sûrement le plugin qui vous manquait. Transformez votre navigateur internet pour visualiser les images et les vid&eacute;os en 3D</span></li>
                                        <li><span class="heure">&raquo; 17h15</span> <span class="titre">Deux avions de la S&eacute;curit&eacute; civile transportant chacun dix personnes ont d&eacute;coll&eacute; vers 10h30, un troisième avion transportant quarante personnes a d&eacute;coll&eacute; peu après.«Ils seront r&eacute;partis sur un ensemble de centres de r&eacute;tention dans le Sud où les familles</span></li>
                                        <li><span class="heure">&raquo; 13h17</span> <span class="titre">Cooliris est sûrement le plugin qui vous manquait. Transformez votre navigateur internet pour visualiser les images et les vid&eacute;os en 3D</span></li>
                                        <li><span class="heure">&raquo; 12h15</span> <span class="titre">Deux avions de la S&eacute;curit&eacute; civile transportant chacun dix personnes ont d&eacute;coll&eacute; vers 10h30, un troisième avion transportant quarante personnes a d&eacute;coll&eacute; peu après.«Ils seront r&eacute;partis sur un ensemble de centres de r&eacute;tention dans le Sud où les familles</span></li>
                                        <li><span class="heure">&raquo; 11h17</span> <span class="titre">Cooliris est sûrement le plugin qui vous manquait. Transformez votre navigateur internet pour visualiser les images et les vid&eacute;os en 3D</span></li>
                                        <li><span class="heure">&raquo; 10h45</span> <span class="titre">Deux avions de la S&eacute;curit&eacute; civile transportant chacun dix personnes ont d&eacute;coll&eacute; vers 10h30, un troisième avion transportant quarante personnes a d&eacute;coll&eacute; peu après.«Ils seront r&eacute;partis sur un ensemble de centres de r&eacute;tention dans le Sud où les familles</span></li>
                                        <li><span class="heure">&raquo; 10h06</span> <span class="titre">Cooliris est sûrement le plugin qui vous manquait. Transformez votre navigateur internet pour visualiser les images et les vid&eacute;os en 3D</span></li>
                                        <li><span class="heure">&raquo; 09h35</span> <span class="titre">Deux avions de la S&eacute;curit&eacute; civile transportant chacun dix personnes ont d&eacute;coll&eacute; vers 10h30, un troisième avion transportant quarante personnes a d&eacute;coll&eacute; peu après.«Ils seront r&eacute;partis sur un ensemble de centres de r&eacute;tention dans le Sud où les familles</span></li>
                                    </ul>
                                </div><!-- :[end] -->                        		
                            </div><!-- reelFilNews:[end] -->                         
