isWindows=1
enableOldClassNaming=
shared_session=
use_error_handler=1
theme=default
dbProfils="dbprofils.ini.php"
modulesPath="lib:jelix-modules/,app:modules/"
pluginsPath="lib:jelix-plugins/,app:plugins/"
trustedModules="jintrospection,jelix,jauth,commun,accueil,contact,forum,actualite,pratique,annonce,rubrique,pack,forfait,credit,projet,culture,newsletter,profil,utilisateur,pays,publication,static,newsletter,membre,service,categorieAn,categorieAct,categorieFor,sujet,commentFor,abonnement,vehicule,immobilier,emploi,candidature,voyage,photo,photoAct"
checkTrustedModules=
timeZone="Europe/Paris"
charset="ISO-8859-1"
locale=fr_FR
startAction=accueilFo_abord
startModule=accueil
[plugins]
auth="auth.plugin.ini.php"
connexionAuto=1
[responses]
html=jResponseHtml
redirect=jResponseRedirect
redirectUrl=jResponseRedirectUrl
binary=jResponseBinary
text=jResponseText
jsonrpc=jResponseJsonrpc
json=jResponseJson
xmlrpc=jResponseXmlrpc
xul=jResponseXul
xuloverlay=jResponseXulOverlay
xuldialog=jResponseXulDialog
xulpage=jResponseXulPage
rdf=jResponseRdf
xml=jResponseXml
zip=jResponseZip
rss2.0=jResponseRss20
atom1.0=jResponseAtom10
css=jResponseCss
ltx2pdf=jResponseLatexToPdf
excel=jResponseExcel
pdf=jResponsePdf
htmlFo=htmlFoResponse
htmlBo=htmlBoResponse
[_coreResponses]
html=jResponseHtml
redirect=jResponseRedirect
redirectUrl=jResponseRedirectUrl
binary=jResponseBinary
text=jResponseText
jsonrpc=jResponseJsonrpc
json=jResponseJson
xmlrpc=jResponseXmlrpc
xul=jResponseXul
xuloverlay=jResponseXulOverlay
xuldialog=jResponseXulDialog
xulpage=jResponseXulPage
rdf=jResponseRdf
xml=jResponseXml
zip=jResponseZip
rss2.0=jResponseRss20
atom1.0=jResponseAtom10
css=jResponseCss
ltx2pdf=jResponseLatexToPdf
excel=jResponseExcel
pdf=jResponsePdf
[error_handling]
messageLogFormat="%date%\t[%code%]\t%msg%\t%file%\t%line%\n"
logFile="error.log"
email="root@localhost"
emailHeaders="Content-Type: text/plain; charset=UTF-8\nFrom: webmaster@yoursite.com\nX-Mailer: Jelix\nX-Priority: 1 (Highest)\n"
quietMessage="Une erreur technique est survenue. Désolé pour ce désagrément."
default="ECHO TRACE LOGFILE EXIT"
error="ECHO TRACE LOGFILE EXIT"
warning="ECHO TRACE LOGFILE"
notice="ECHO TRACE LOGFILE"
strict="ECHO TRACE LOGFILE"
exception="ECHO TRACE LOGFILE"
[compilation]
checkCacheFiletime=1
force=
[urlengine]
engine=significant
enableParser=1
multiview=
basePath="/projects/jelix/ilay-nosy/www/"
jelixWWWPath="/projects/jelix/ilay-nosy/www/jelix/"
defaultEntrypoint=index
entrypointExtension=".php"
notfoundAct="jelix~error_notfound"
useIIS=
IISPathKey=__JELIX_URL__
IISStripslashes_path_key=1
simple_urlengine_https=
[simple_urlengine_entrypoints]
index="@classic"
xmlrpc="@xmlrpc"
jsonrpc="@jsonrpc"
rdf="@rdf"
[logfiles]
default="messages.log"
[mailer]
mailerType=mail
hostname=
sendmailPath="/usr/sbin/sendmail"
smtpHost=localhost
smtpPort=25
smtpHelo=
smtpAuth=
smtpUsername=
smtpPassword=
smtpTimeout=10
[acl]
driver=db
[_allBasePath]
0="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\lib/jelix-modules/"
1="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/"
2="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\lib/jelix-plugins/acl/"
3="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\lib/jelix-plugins/auth/"
4="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\lib/jelix-plugins/coord/"
5="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\lib/jelix-plugins/db/"
6="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\lib/jelix-plugins/tpl/"
7="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\lib/jelix-plugins/urls/"
8="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\lib/jelix-plugins/wr_rules/"
9="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\plugins/auth/"
10="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\plugins/coord/"
11="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\plugins/db/"
12="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\plugins/tpl/"
[_modulesPathList]
jelix="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\lib\jelix/core-modules/jelix/"
jauth="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\lib/jelix-modules/jauth/"
jintrospection="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\lib/jelix-modules/jintrospection/"
junittests="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\lib/jelix-modules/junittests/"
abonnement="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/abonnement/"
accueil="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/accueil/"
actualite="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/actualite/"
annonce="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/annonce/"
banniere="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/banniere/"
candidature="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/candidature/"
categorieAct="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/categorieAct/"
categorieAn="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/categorieAn/"
categorieCult="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/categorieCult/"
categorieFor="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/categorieFor/"
categorieOff="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/categorieOff/"
commentAct="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/commentAct/"
commentFor="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/commentFor/"
commentOff="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/commentOff/"
commun="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/commun/"
contact="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/contact/"
credit="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/credit/"
culture="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/culture/"
emploi="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/emploi/"
forfait="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/forfait/"
forum="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/forum/"
immobilier="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/immobilier/"
marque="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/marque/"
membre="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/membre/"
modele="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/modele/"
newsletter="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/newsletter/"
officiel="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/officiel/"
pack="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/pack/"
pays="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/pays/"
petiteAnnonce="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/petiteAnnonce/"
petiteAnnonce_old="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/petiteAnnonce_old/"
photo="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/photo/"
photoAct="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/photoAct/"
photoOff="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/photoOff/"
pratique="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/pratique/"
profil="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/profil/"
projet="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/projet/"
publication="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/publication/"
rubrique="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/rubrique/"
service="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/service/"
session="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/session/"
static="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/static/"
sujet="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/sujet/"
utilisateur="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/utilisateur/"
vehicule="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/vehicule/"
visite="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/visite/"
voyage="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\modules/voyage/"
[_pluginsPathList_acl]
db="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\lib\jelix/plugins/acl/db/"
[_pluginsPathList_auth]
class="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\lib\jelix/plugins/auth/class/"
db="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\lib\jelix/plugins/auth/db/"
lds="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\lib\jelix/plugins/auth/lds/"
[_pluginsPathList_coord]
auth="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\lib\jelix/plugins/coord/auth/"
autolocale="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\lib\jelix/plugins/coord/autolocale/"
magicquotes="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\lib\jelix/plugins/coord/magicquotes/"
connexionAuto="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\plugins/coord/connexionAuto/"
_notes="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\plugins/coord/_notes/"
[_pluginsPathList_db]
intuition="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\lib\jelix/plugins/db/intuition/"
mysql="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\lib\jelix/plugins/db/mysql/"
postgresql="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\lib\jelix/plugins/db/postgresql/"
sqlite="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\lib\jelix/plugins/db/sqlite/"
[_tplpluginsPathList_common]
0="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\lib\jelix/plugins/tpl/common/"
1="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\plugins/tpl/common/"
[_tplpluginsPathList_html]
0="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\lib\jelix/plugins/tpl/html/"
1="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\plugins/tpl/html/"
[_tplpluginsPathList_ltx2pdf]
0="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\lib\jelix/plugins/tpl/ltx2pdf/"
[_tplpluginsPathList_text]
0="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\lib\jelix/plugins/tpl/text/"
1="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\plugins/tpl/text/"
[_tplpluginsPathList_xul]
0="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\lib\jelix/plugins/tpl/xul/"
[_pluginsPathList_urls]
significant="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\lib\jelix/plugins/urls/significant/"
simple="C:\Program Files (x86)\EasyPHP-5.3.8.1\www\projects\jelix\ilay-nosy\lib\jelix/plugins/urls/simple/"
[_trustedModules]
0=jelix
1=jauth
2=jintrospection
3=junittests
4=abonnement
5=accueil
6=actualite
7=annonce
8=banniere
9=candidature
10=categorieAct
11=categorieAn
12=categorieCult
13=categorieFor
14=categorieOff
15=commentAct
16=commentFor
17=commentOff
18=commun
19=contact
20=credit
21=culture
22=emploi
23=forfait
24=forum
25=immobilier
26=marque
27=membre
28=modele
29=newsletter
30=officiel
31=pack
32=pays
33=petiteAnnonce
34=petiteAnnonce_old
35=photo
36=photoAct
37=photoOff
38=pratique
39=profil
40=projet
41=publication
42=rubrique
43=service
44=session
45=static
46=sujet
47=utilisateur
48=vehicule
49=visite
50=voyage
